services:
  app:
    container_name: gym-tracker
    build:
      context: ./GymTracker
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5046:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - gym-tracker-network

  db:
    container_name: gym-tracker-db
    restart: always
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
    env_file:
      - .env
    volumes:
      - sqlserver:/var/opt/mssql
    networks:
      - gym-tracker-network

volumes:
  sqlserver:

networks:
  gym-tracker-network:
    driver: bridge
