name: Deploy to Private Server

on:
  push:
    tags:
      - 'v*'

env:
  DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore GymTracker/GymTracker.csproj

    - name: Create .env file
      run: |
        echo "DB_USER=${{ secrets.DB_USER }}" > .env
        echo "MSSQL_SA_PASSWORD=${{ secrets.MSSQL_SA_PASSWORD }}" >> .env
    
    - name: Build project
      run: dotnet build GymTracker/GymTracker.csproj --configuration Release --no-restore
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    
    - name: Deploy to Server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
      run: |
        rsync -avz --delete -e "ssh -p $SERVER_PORT" \
          --exclude='.git' \
          --exclude='obj' \
          --exclude='bin/Debug' \
          ./ $SERVER_USER@$SERVER_IP:$DEPLOY_PATH
    
    - name: Restart Application
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
      run: |
        ssh -p $SERVER_PORT $SERVER_USER@$SERVER_IP << EOF
          cd $DEPLOY_PATH
          docker-compose down && docker-compose up -d --build
        EOF